# Generated by Django 3.0.5 on 2021-06-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='platform',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='movie.StreamPlatforms'),
            preserve_default=False,
        ),
    ]
